// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtd_WK6S7UgO9gkpIZ8n3vWmrtacVJ48o',
    appId: '1:943483376752:web:b4566a6ef1ebb854bdd0b5',
    messagingSenderId: '943483376752',
    projectId: 'ecomm-shopping-app',
    authDomain: 'ecomm-shopping-app.firebaseapp.com',
    storageBucket: 'ecomm-shopping-app.appspot.com',
    measurementId: 'G-DBCMPC3HHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoYnFTap1Ml9o8zk4d2565pvw1aBnMHQ',
    appId: '1:943483376752:android:68e6866b1241f361bdd0b5',
    messagingSenderId: '943483376752',
    projectId: 'ecomm-shopping-app',
    storageBucket: 'ecomm-shopping-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPo8krZ3lARYB64Ca3M9u8CHXWg6590z0',
    appId: '1:943483376752:ios:a68a53a606948e64bdd0b5',
    messagingSenderId: '943483376752',
    projectId: 'ecomm-shopping-app',
    storageBucket: 'ecomm-shopping-app.appspot.com',
    iosClientId: '943483376752-qfl0t741jpu9kf6m9i2npdgasriajl2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPo8krZ3lARYB64Ca3M9u8CHXWg6590z0',
    appId: '1:943483376752:ios:a68a53a606948e64bdd0b5',
    messagingSenderId: '943483376752',
    projectId: 'ecomm-shopping-app',
    storageBucket: 'ecomm-shopping-app.appspot.com',
    iosClientId: '943483376752-qfl0t741jpu9kf6m9i2npdgasriajl2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothingapp',
  );
}
